import React from 'react';
import Link from 'next/link';

export default function PrivacyPage() {
  return (
    <div className="bg-[#1b1b1b] text-[#dfdfdf] mx-auto">
      <div className="max-w-4xl mx-auto py-8 px-4">
        <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
        <p className="mb-6">Last Updated: March 21, 2025</p>
        
        <div className="space-y-8">
          <section>
            <h2 className="text-2xl font-semibold mb-4">1. Introduction</h2>
            <p className="mb-3">
              Zero Human (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to protecting your privacy. This Privacy Policy explains how we collect, 
              use, disclose, and safeguard your information when you use our AI-powered creative advertisement platform, website, 
              and related services (collectively, the &quot;Services&quot;).
            </p>
            <p className="mb-3">
              By accessing or using our Services, you acknowledge that you have read, understood, and agree to be bound by this Privacy Policy. 
              If you do not agree with our policies and practices, please do not use our Services.
            </p>
            <p className="mb-3">
              This Privacy Policy may change from time to time. We will notify you of any changes by posting the new Privacy Policy on this page 
              and updating the &quot;Last Updated&quot; date. You are advised to review this Privacy Policy periodically for any changes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">2. Information We Collect</h2>
            <p className="mb-3">We collect several types of information from and about users of our Services, including:</p>
            
            <h3 className="text-xl font-semibold mb-2">2.1 Personal Information</h3>
            <p className="mb-3">
              Personal information is data that can be used to identify you directly or indirectly. We may collect the following personal information:
            </p>
            <ul className="list-disc pl-6 mb-3 space-y-2">
              <li>Contact information (such as name, email address, phone number, and business address)</li>
              <li>Account credentials (such as username and password)</li>
              <li>Billing information (such as credit card details and billing address)</li>
              <li>Professional information (such as company name, job title, and industry)</li>
              <li>Identity verification information as required by applicable laws</li>
            </ul>
            
            <h3 className="text-xl font-semibold mb-2">2.2 Usage Data</h3>
            <p className="mb-3">
              We may automatically collect certain information about how you access and use our Services, including:
            </p>
            <ul className="list-disc pl-6 mb-3 space-y-2">
              <li>Device information (such as IP address, browser type, operating system, and device identifiers)</li>
              <li>Usage information (such as pages visited, features used, time spent on the Services, and referring URLs)</li>
              <li>Performance data (such as crash reports, system activity, and hardware settings)</li>
            </ul>
            
            <h3 className="text-xl font-semibold mb-2">2.3 User Content</h3>
            <p className="mb-3">
              We collect information and content that you provide when using our Services, including:
            </p>
            <ul className="list-disc pl-6 mb-3 space-y-2">
              <li>Inputs and specifications you provide to generate content</li>
              <li>Files you upload to our Services</li>
              <li>Preferences and settings you configure for our Services</li>
              <li>Communications you have with us or other users through our Services</li>
            </ul>
            
            <h3 className="text-xl font-semibold mb-2">2.4 Generated Content</h3>
            <p className="mb-3">
              <strong>Important:</strong> We collect and retain all content generated by our AI technology based on your inputs 
              (&quot;Generated Content&quot;). This includes all digital models, advertisements, and other creative assets produced through our Services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">3. How We Collect Information</h2>
            <p className="mb-3">We collect information through:</p>
            <ul className="list-disc pl-6 mb-3 space-y-2">
              <li>Direct interactions when you provide information to us</li>
              <li>Automated technologies and interactions (such as cookies and similar tracking technologies)</li>
              <li>Third-party sources (such as business partners, analytics providers, and identity verification services)</li>
            </ul>
            
            <h3 className="text-xl font-semibold mb-2">3.1 Cookies and Similar Technologies</h3>
            <p className="mb-3">
              We use cookies and similar tracking technologies to track activity on our Services and to hold certain information. 
              Cookies are files with a small amount of data that may include an anonymous unique identifier.
            </p>
            <p className="mb-3">
              We use the following types of cookies:
            </p>
            <ul className="list-disc pl-6 mb-3 space-y-2">
              <li>Essential cookies: Necessary for the operation of our Services</li>
              <li>Analytical/performance cookies: Allow us to recognize and count visitors and analyze how users interact with our Services</li>
              <li>Functionality cookies: Used to recognize you when you return to our Services</li>
              <li>Targeting cookies: Record your visit to our Services, the pages you visit, and the links you follow</li>
            </ul>
            <p className="mb-3">
              You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, 
              you may not be able to use some portions of our Services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">4. How We Use Your Information</h2>
            <p className="mb-3">We use the information we collect for various purposes, including:</p>
            
            <h3 className="text-xl font-semibold mb-2">4.1 Providing and Improving Our services</h3>
            <ul className="list-disc pl-6 mb-3 space-y-2">
              <li>To provide, maintain, and improve our Services</li>
              <li>To process transactions and manage your account</li>
              <li>To personalize your experience and deliver content relevant to your interests</li>
              <li>To develop new products, services, features, and functionality</li>
              <li>To monitor and analyze trends, usage, and activities in connection with our Services</li>
            </ul>
            
            <h3 className="text-xl font-semibold mb-2">4.2 Communications</h3>
            <ul className="list-disc pl-6 mb-3 space-y-2">
              <li>To communicate with you about our Services, including sending updates, security alerts, and support messages</li>
              <li>To respond to your inquiries, comments, feedback, or questions</li>
              <li>To send marketing communications, promotional offers, newsletters, and other information that may be of interest to you</li>
            </ul>
            
            <h3 className="text-xl font-semibold mb-2">4.3 Security and Compliance</h3>
            <ul className="list-disc pl-6 mb-3 space-y-2">
              <li>To protect the security and integrity of our Services</li>
              <li>To detect, prevent, and address technical issues, security breaches, and fraudulent or illegal activity</li>
              <li>To verify your identity and prevent fraud or unauthorized access</li>
              <li>To comply with legal obligations and enforce our terms and policies</li>
            </ul>
            
            <h3 className="text-xl font-semibold mb-2">4.4 AI Training and Improvement</h3>
            <p className="mb-3">
              <strong>Important:</strong> We may use your User Content and Generated Content to train, improve, and develop our AI models 
              and technologies. This includes using Generated Content for future training purposes, service improvements, quality control, 
              and research and development.
            </p>
            <p className="mb-3">
              By using our Services, you expressly consent to the use of Generated Content for AI training purposes as described above. 
              This consent is a condition of using our Services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">5. How We Share Your Information</h2>
            <p className="mb-3">We may share your information in the following circumstances:</p>
            
            <h3 className="text-xl font-semibold mb-2">5.1 Service Providers</h3>
            <p className="mb-3">
              We may share your information with third-party vendors, service providers, contractors, or agents who perform services for us 
              or on our behalf and require access to such information to do that work. Examples include payment processing, data analysis, 
              email delivery, hosting services, customer service, and marketing efforts.
            </p>
            
            <h3 className="text-xl font-semibold mb-2">5.2 Business Transfers</h3>
            <p className="mb-3">
              If we are involved in a merger, acquisition, financing, reorganization, bankruptcy, receivership, sale of company assets, 
              or transition of service to another provider, your information may be transferred or sold as part of that transaction. 
              We will notify you of any such change in ownership or control of your personal information.
            </p>
            
            <h3 className="text-xl font-semibold mb-2">5.3 Legal Requirements</h3>
            <p className="mb-3">
              We may disclose your information where required to do so by law or in response to valid requests by public authorities 
              (e.g., a court or a government agency).
            </p>
            
            <h3 className="text-xl font-semibold mb-2">5.4 With Your Consent</h3>
            <p className="mb-3">
              We may share your information with your consent or at your direction.
            </p>
            
            <h3 className="text-xl font-semibold mb-2">5.5 Aggregated or De-identified Data</h3>
            <p className="mb-3">
              We may share aggregated or de-identified information that cannot reasonably be used to identify you.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">6. Data Retention</h2>
            <p className="mb-3">
              We will retain your personal information for as long as necessary to fulfill the purposes for which we collected it, 
              including for the purposes of satisfying any legal, accounting, or reporting requirements.
            </p>
            <p className="mb-3">
              To determine the appropriate retention period for personal information, we consider the amount, nature, and sensitivity of the personal information, 
              the potential risk of harm from unauthorized use or disclosure of your personal information, the purposes for which we process your personal information, 
              and whether we can achieve those purposes through other means, and the applicable legal requirements.
            </p>
            <p className="mb-3">
              <strong>Important:</strong> We may retain Generated Content indefinitely for AI training purposes, even after you have terminated your account or 
              relationship with us, unless prohibited by applicable law.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">7. Data Security</h2>
            <p className="mb-3">
              We have implemented appropriate technical and organizational security measures designed to protect the security of any personal 
              information we process. However, please also remember that no method of transmission over the Internet or method of electronic 
              storage is 100% secure. While we strive to use commercially acceptable means to protect your personal information, we cannot 
              guarantee its absolute security.
            </p>
            <p className="mb-3">
              We regularly monitor our systems for possible vulnerabilities and attacks and regularly review our security measures. If you have 
              reason to believe that your interaction with us is no longer secure, please immediately notify us by contacting us using the information 
              provided in the &quot;Contact Information&quot; section.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">8. Your Data Protection Rights</h2>
            <p className="mb-3">
              Depending on your location and subject to applicable law, you may have the following rights with respect to your personal information:
            </p>
            
            <h3 className="text-xl font-semibold mb-2">8.1 Access and Portability</h3>
            <p className="mb-3">
              You may have the right to access and receive a copy of the personal information we hold about you.
            </p>
            
            <h3 className="text-xl font-semibold mb-2">8.2 Rectification</h3>
            <p className="mb-3">
              You may have the right to request correction of any inaccurate or incomplete personal information that we hold about you.
            </p>
            
            <h3 className="text-xl font-semibold mb-2">8.3 Erasure</h3>
            <p className="mb-3">
              You may have the right to request that we delete your personal information in certain circumstances, such as when it is no longer 
              necessary for the purposes for which it was collected.
            </p>
            
            <h3 className="text-xl font-semibold mb-2">8.4 Restriction</h3>
            <p className="mb-3">
              You may have the right to request that we restrict the processing of your personal information in certain circumstances, 
              such as when you contest the accuracy of your personal information.
            </p>
            
            <h3 className="text-xl font-semibold mb-2">8.5 Objection</h3>
            <p className="mb-3">
              You may have the right to object to the processing of your personal information in certain circumstances, such as when 
              the processing is based on our legitimate interests.
            </p>
            
            <h3 className="text-xl font-semibold mb-2">8.6 Withdrawal of Consent</h3>
            <p className="mb-3">
              If we are processing your personal information based on your consent, you may have the right to withdraw your consent at any time. 
              This will not affect the lawfulness of processing based on consent before its withdrawal.
            </p>
            
            <h3 className="text-xl font-semibold mb-2">8.7 Complaint</h3>
            <p className="mb-3">
              You may have the right to lodge a complaint with a supervisory authority if you believe that our processing of your personal 
              information violates applicable law.
            </p>
            
            <p className="mb-3">
              To exercise any of these rights, please contact us using the information provided in the &quot;Contact Information&quot; section. 
              We may need to verify your identity before responding to your request.
            </p>
            
            <p className="mb-3">
              <strong>Important:</strong> Please note that these rights may be limited in certain circumstances, such as when we have a legal 
              obligation to retain certain information. Additionally, as mentioned in Section 4.4 and 6, we may continue to use Generated 
              Content for AI training purposes even after you have requested deletion of your personal information.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">9. International Transfers</h2>
            <p className="mb-3">
              Our Services are operated and managed on servers located in the United States. If you access or use our Services from outside the United States, 
              your information may be transferred to, stored, and processed in the United States or other countries where our service providers maintain facilities.
            </p>
            <p className="mb-3">
              By using our Services, you consent to the transfer of information to countries outside your country of residence, including the United States, 
              which may have data protection rules that are different from those of your country. We will take appropriate measures to protect your personal 
              information in accordance with this Privacy Policy.
            </p>
            <p className="mb-3">
              For transfers from the European Economic Area (EEA), United Kingdom, or Switzerland to countries not deemed to provide an adequate level of data protection, 
              we rely on appropriate safeguards, such as Standard Contractual Clauses adopted by the European Commission, to transfer your information.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">10. Children&apos;s Privacy</h2>
            <p className="mb-3">
              Our Services are not intended for children under the age of 16. We do not knowingly collect personal information from children under 16. 
              If you are a parent or guardian and believe that your child has provided us with personal information, please contact us using the 
              information provided in the &quot;Contact Information&quot; section. If we become aware that we have collected personal information from children 
              without verification of parental consent, we will take steps to remove that information from our servers.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">11. California Privacy Rights</h2>
            <p className="mb-3">
              If you are a California resident, you may have additional rights under the California Consumer Privacy Act (CCPA) and the California Privacy Rights Act (CPRA) 
              regarding your personal information.
            </p>
            
            <h3 className="text-xl font-semibold mb-2">11.1 Additional Disclosures</h3>
            <p className="mb-3">
              In the preceding 12 months, we have collected, disclosed, and sold (as defined under the CCPA/CPRA) the categories of personal information described in 
              Section 2 of this Privacy Policy. For details about the categories of third parties with whom we share such information, please see Section 5.
            </p>
            
            <h3 className="text-xl font-semibold mb-2">11.2 Additional Rights</h3>
            <p className="mb-3">
              As a California resident, you have the right to:
            </p>
            <ul className="list-disc pl-6 mb-3 space-y-2">
              <li>Request information about the personal information we collect, use, disclose, and sell</li>
              <li>Request deletion of your personal information (subject to certain exceptions)</li>
              <li>Opt-out of the sale or sharing of your personal information</li>
              <li>Not be discriminated against for exercising your privacy rights</li>
              <li>Correct inaccurate personal information</li>
              <li>Limit the use and disclosure of sensitive personal information</li>
            </ul>
            
            <p className="mb-3">
              To exercise these rights, please contact us using the information provided in the &quot;Contact Information&quot; section.
            </p>
            
            <h3 className="text-xl font-semibold mb-2">11.3 Shine the Light</h3>
            <p className="mb-3">
              California&apos;s &quot;Shine the Light&quot; law (Civil Code Section &sect; 1798.83) permits users of our Services that are California residents to request certain 
              information regarding our disclosure of personal information to third parties for their direct marketing purposes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">12. Do Not Track Signals</h2>
            <p className="mb-3">
              Some web browsers have a &quot;Do Not Track&quot; feature that signals to websites that you visit that you do not want to have your online activity tracked. 
              Due to differences in how web browsers incorporate and activate this feature, it is not always clear whether users intend for these signals to be 
              transmitted, or whether they are aware of them. We currently do not respond to Do Not Track signals.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">13. Third-Party Websites and Services</h2>
            <p className="mb-3">
              Our Services may contain links to third-party websites and services that are not owned or controlled by us. We have no control over, and assume no responsibility for, 
              the content, privacy policies, or practices of any third-party websites or services. You should review the privacy policies of these third-party sites before providing 
              any information to them. We encourage you to be aware when you leave our Services and to read the privacy policies of each website you visit.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">14. Contact Information</h2>
            <p className="mb-3">
              If you have any questions, concerns, or comments about this Privacy Policy or our privacy practices, please contact us at:
            </p>
            <div className="mb-3">
              <p>Zero Human</p>
              <p>Email: <Link href="mailo: info@zerohuman.co"><u>info@zerohuman.co</u></Link></p>
            </div>
            <p className="mb-3">
              For data protection inquiries specifically, you can contact our Data Protection Officer at <Link href="mailo: info@zerohuman.co">info@zerohuman.co</Link>.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">15. Changes to this Privacy Policy</h2>
            <p className="mb-3">
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating 
              the &quot;Last Updated&quot; date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to 
              this Privacy Policy are effective when they are posted on this page.
            </p>
            <p className="mb-3">
              If we make material changes to this Privacy Policy, we will notify you either through the email address you have provided us or by placing a 
              prominent notice on our website.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
