import { Link } from 'lucide-react';
import React from 'react';

export default function Terms() {
  return (
    <div className="bg-[#1b1b1b] text-[#dfdfdf] mx-auto">
      <div className="max-w-4xl mx-auto py-8 px-4">
        <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
        <p className="mb-6">Last Updated: March 21, 2025</p>
        
        <div className="space-y-8">
          <section>
            <h2 className="text-2xl font-semibold mb-4">1. Introduction</h2>
            <p className="mb-3">
              Welcome to Zero Human. These Terms of Service (&amp;quot;Terms&amp;quot;) govern your access to and use of the Zero Human platform, 
              website, and services (collectively, the &amp;quot;Services&amp;quot;). By accessing or using our Services, you agree to be bound 
              by these Terms and our Privacy Policy.
            </p>
            <p className="mb-3">
              Zero Human is an AI-powered creative advertisement platform that produces digital content including 
              but not limited to digital models, advertisements, and other creative assets.
            </p>
            <p className="mb-3">
              Please read these Terms carefully. If you do not agree with these Terms, you may not access or use our Services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">2. Definitions</h2>
            <div className="space-y-2">
              <p>&amp;quot;Zero Human,&amp;quot; &amp;quot;we,&amp;quot; &amp;quot;us,&amp;quot; or &amp;quot;our&amp;quot; refers to Zero Human and its affiliates, directors, officers, employees, and agents.</p>
              <p>&amp;quot;You&amp;quot; refers to any individual or entity that accesses or uses our Services.</p>
              <p>&amp;quot;Content&amp;quot; refers to any text, graphics, images, music, software, audio, video, information, or other materials generated by or through our Services.</p>
              <p>&amp;quot;User Content&amp;quot; refers to content that you submit or transmit through our Services.</p>
              <p>&amp;quot;Generated Content&amp;quot; refers to content that is created by our AI technology based on your inputs or specifications.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">3. Eligibility</h2>
            <p className="mb-3">
              You must be at least 18 years old to use our Services. By using our Services, you represent and warrant that you meet this requirement 
              and that you have the right, authority, and capacity to enter into these Terms.
            </p>
            <p className="mb-3">
              If you are using the Services on behalf of an organization, you represent and warrant that you have the authority to bind that 
              organization to these Terms, and you agree to be bound by these Terms on behalf of that organization.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">4. Account Registration</h2>
            <p className="mb-3">
              You may need to create an account to use certain features of our Services. You agree to provide accurate, current, and complete 
              information during the registration process and to update such information to keep it accurate, current, and complete.
            </p>
            <p className="mb-3">
              You are responsible for safeguarding your account credentials and for any activity that occurs under your account. You agree to 
              notify us immediately of any unauthorized access to or use of your account or credentials.
            </p>
            <p className="mb-3">
              We reserve the right to disable any user account at any time if, in our opinion, you have violated any provision of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">5. Services and Subscription</h2>
            <p className="mb-3">
              Zero Human offers AI-powered creative advertisement services as described on our website. We may offer different subscription 
              tiers with varying features and limitations.
            </p>
            <p className="mb-3">
              We reserve the right to modify, suspend, or discontinue any part of our Services at any time, with or without notice. We will not 
              be liable to you or any third party for any modification, suspension, or discontinuation of our Services.
            </p>
            <p className="mb-3">
              Subscription fees are non-refundable except as expressly provided in these Terms or as required by applicable law. You may cancel 
              your subscription at any time, but you will not receive a refund for the current billing cycle.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">6. User Content and Generated Content</h2>
            <p className="mb-3">
              You retain ownership of any User Content you submit to our Services. By submitting User Content, you grant us a worldwide, 
              non-exclusive, royalty-free, sublicensable, and transferable license to use, reproduce, distribute, prepare derivative works of, 
              display, and perform your User Content in connection with the Services and our business operations.
            </p>
            <p className="mb-3">
              <strong>Important:</strong> All Generated Content produced by Zero Human&apos;s AI technology based on your inputs is subject to the 
              following terms:
            </p>
            <ol className="list-decimal pl-6 mb-3 space-y-2">
              <li>You receive a license to use the Generated Content for your business purposes, subject to the restrictions in these Terms.</li>
              <li>Zero Human retains ownership of all Generated Content and the underlying AI technology.</li>
              <li>You agree that Zero Human has the right to use all Generated Content for future training purposes, service improvements, 
                  quality control, and research and development without additional compensation to you.</li>
              <li>This right extends to all derivatives and modifications of the Generated Content.</li>
            </ol>
            <p className="mb-3">
              You represent and warrant that you have all necessary rights, licenses, consents, and permissions to submit User Content and to 
              grant the licenses described above.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">7. Acceptable Use</h2>
            <p className="mb-3">You agree not to use our Services to:</p>
            <ul className="list-disc pl-6 mb-3 space-y-2">
              <li>Create, upload, or transmit any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, 
                  invasive of another&apos;s privacy, hateful, or racially, ethnically, or otherwise objectionable.</li>
              <li>Impersonate any person or entity or falsely state or otherwise misrepresent your affiliation with a person or entity.</li>
              <li>Create or transmit unsolicited commercial messages or &amp;quot;spam.&amp;quot;</li>
              <li>Violate any applicable laws, regulations, or third-party rights.</li>
              <li>Attempt to bypass or circumvent any security measures or access restrictions of our Services.</li>
              <li>Use our Services to create content that could be deemed misleading, deceptive, or fraudulent.</li>
              <li>Use our Services to create deepfakes or other synthetic content that could be used to harm individuals or spread misinformation.</li>
              <li>Create content that infringes on intellectual property rights of others.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">8. Intellectual Property Rights</h2>
            <p className="mb-3">
              The Services, including all content, features, and functionality, are owned by Zero Human, its licensors, or other providers 
              and are protected by copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.
            </p>
            <p className="mb-3">
              These Terms do not grant you any right, title, or interest in or to the Services or any content provided by Zero Human, except 
              for the limited license expressly set forth in these Terms.
            </p>
            <p className="mb-3">
              Zero Human respects the intellectual property rights of others and expects users of our Services to do the same. We reserve the 
              right to remove content that infringes on the intellectual property rights of others.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">9. AI-Generated Content Considerations</h2>
            <p className="mb-3">
              You acknowledge that our Services utilize artificial intelligence to generate content and that such technology has limitations:
            </p>
            <ul className="list-disc pl-6 mb-3 space-y-2">
              <li>Generated Content may not always meet your specific requirements or expectations.</li>
              <li>Zero Human does not guarantee the accuracy, completeness, or suitability of Generated Content for any particular purpose.</li>
              <li>You are responsible for reviewing and verifying all Generated Content before use.</li>
              <li>Zero Human is not liable for any consequences resulting from your use of Generated Content.</li>
            </ul>
            <p className="mb-3">
              You agree to use Generated Content responsibly and in compliance with applicable laws and regulations, including but not limited to 
              laws regarding advertising, consumer protection, data privacy, and intellectual property.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">10. Disclaimer of Warranties</h2>
            <p className="mb-3">
              THE SERVICES ARE PROVIDED &amp;quot;AS IS&amp;quot; AND &amp;quot;AS AVAILABLE&amp;quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT 
              LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
            </p>
            <p className="mb-3">
              ZERO HUMAN DOES NOT WARRANT THAT THE SERVICES WILL FUNCTION UNINTERRUPTED, ERROR-FREE, OR THAT DEFECTS WILL BE CORRECTED. 
              WE DO NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE SERVICES IN TERMS OF CORRECTNESS, 
              ACCURACY, RELIABILITY, OR OTHERWISE.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">11. Limitation of Liability</h2>
            <p className="mb-3">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ZERO HUMAN AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, PARTNERS, AND 
              LICENSORS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED 
              TO, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
            </p>
            <ol className="list-decimal pl-6 mb-3 space-y-2">
              <li>YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICES;</li>
              <li>ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICES;</li>
              <li>ANY CONTENT OBTAINED FROM THE SERVICES; AND</li>
              <li>UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT.</li>
            </ol>
            <p className="mb-3">
              IN NO EVENT SHALL ZERO HUMAN&apos;S TOTAL LIABILITY TO YOU FOR ALL CLAIMS EXCEED THE AMOUNT PAID BY YOU, IF ANY, TO ACCESS OR USE 
              THE SERVICES DURING THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE LIABILITY.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">12. Indemnification</h2>
            <p className="mb-3">
              You agree to indemnify, defend, and hold harmless Zero Human and its officers, directors, employees, agents, and affiliates from 
              and against any and all claims, liabilities, damages, losses, costs, expenses, or fees (including reasonable attorneys&apos; fees) 
              arising from:
            </p>
            <ol className="list-decimal pl-6 mb-3 space-y-2">
              <li>Your use of or access to the Services;</li>
              <li>Your violation of these Terms;</li>
              <li>Your violation of any third-party rights, including without limitation any intellectual property rights or privacy rights;</li>
              <li>Your use of Generated Content; or</li>
              <li>Any content you submit to the Services.</li>
            </ol>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">13. Term and Termination</h2>
            <p className="mb-3">
              These Terms will remain in full force and effect while you use the Services. We may terminate or suspend your access to the 
              Services immediately, without prior notice or liability, for any reason, including but not limited to a breach of these Terms.
            </p>
            <p className="mb-3">
              Upon termination, your right to use the Services will immediately cease. If you wish to terminate your account, you may simply 
              discontinue using the Services or contact us to request account deletion.
            </p>
            <p className="mb-3">
              All provisions of these Terms which by their nature should survive termination shall survive termination, including, without 
              limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">14. Governing Law and Dispute Resolution</h2>
            <p className="mb-3">
              These Terms shall be governed by and construed in accordance with the laws of Bahrian jurisdiction, without regard to its conflict of law provisions.
            </p>
            <p className="mb-3">
              Any dispute arising out of or relating to these Terms or the Services shall be resolved through binding arbitration conducted by arbitration body 
              in accordance with its commercial arbitration rules. The arbitration shall be conducted in Bahrian.
            </p>
            <p className="mb-3">
              The arbitrator&apos;s award shall be binding and may be entered as a judgment in any court of competent jurisdiction. To the fullest extent 
              permitted by applicable law, no arbitration under these Terms shall be joined to an arbitration involving any other party subject to 
              these Terms, whether through class arbitration proceedings or otherwise.
            </p>
            <p className="mb-3">
              Notwithstanding the foregoing, we may seek injunctive or other equitable relief to protect our intellectual property rights in any 
              court of competent jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">15. Changes to Terms</h2>
            <p className="mb-3">
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any material 
              changes to these Terms by posting the updated Terms on our website and changing the &amp;quot;Last Updated&amp;quot; date.
            </p>
            <p className="mb-3">
              Your continued use of the Services after any such changes constitutes your acceptance of the new Terms. If you do not agree to the 
              new Terms, you must stop using the Services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">16. Contact Information</h2>
            <p className="mb-3">
              If you have any questions about these Terms, please contact us at <a href="mailto:info@zerohuman.co"><b><u>info@zerohuman.co</u></b></a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
